/**
 * WAF fingerprint database.
 *
 * Each entry maps a WAF vendor name to response signatures that
 * help identify it. When sqlmap probes a target, we parse the
 * response headers, body, and status codes against these patterns.
 *
 * Sources: sqlmap's own WAF detection, wafw00f, manual research.
 */

export interface WafSignature {
  /** Human-readable WAF name */
  name: string;
  /** Known product/company names */
  vendor: string;
  /** Response headers that indicate this WAF */
  headers: Record<string, string>;
  /** HTTP status codes commonly returned when blocked */
  codes: number[];
  /** Body regex patterns that indicate blocking by this WAF */
  bodyPatterns: string[];
  /** Cookies set by this WAF */
  cookies: string[];
  /** CSS selectors / HTML markers in block pages */
  htmlMarkers: string[];
}

export interface WafDetectionResult {
  detected: boolean;
  name: string | null;
  vendor: string | null;
  confidence: number; // 0-100
  evidence: string[];
  allMatches: Array<{ name: string; confidence: number }>;
}

export const WAF_SIGNATURES: WafSignature[] = [
  {
    name: "Cloudflare",
    vendor: "Cloudflare, Inc.",
    headers: {
      "cf-ray": "",
      "cf-cache-status": "",
      "cf-connecting-ip": "",
      "server": "cloudflare",
      "cf-chl-bypass": "",
    },
    codes: [403, 503],
    bodyPatterns: [
      "Cloudflare Ray ID:",
      "Attention Required! \\| Cloudflare",
      "DDoS protection by Cloudflare",
      "cf-browser-verify",
      "Checking your browser",
      "Please turn JavaScript on and reload the page",
    ],
    cookies: ["__cfduid", "__cf_bm", "cf_clearance", "__cflb"],
    htmlMarkers: ["#cf-error-details", ".cf-browser-verification", ".cf-wrapper"],
  },
  {
    name: "AWS WAF",
    vendor: "Amazon Web Services",
    headers: {
      "x-amzn-requestid": "",
      "x-amz-cf-id": "",
      "x-amz-cf-pop": "",
      "server": "CloudFront",
    },
    codes: [403],
    bodyPatterns: [
      "Request blocked.",
      "AWS WAF",
      "The request was blocked by AWS WAF",
      "x-amzn-ErrorType",
    ],
    cookies: ["aws-waf-token"],
    htmlMarkers: [],
  },
  {
    name: "ModSecurity",
    vendor: "Trustwave / OWASP",
    headers: {},
    codes: [403, 406, 501],
    bodyPatterns: [
      "ModSecurity",
      "This error was generated by Mod_Security",
      "Not Acceptable!",
      "406 Not Acceptable",
      "ModSecurity Action",
      "ModSecurity:",
    ],
    cookies: [],
    htmlMarkers: [],
  },
  {
    name: "Imperva / Incapsula",
    vendor: "Imperva, Inc.",
    headers: {
      "x-iinfo": "",
      "x-cdn": "Incapsula",
    },
    codes: [403, 406],
    bodyPatterns: [
      "Incapsula incident ID:",
      "Error code 15",
      "Error code 16",
      "_Incapsula_Resource",
      "Request unsuccessful.",
      "incap_ses_",
    ],
    cookies: ["incap_ses_", "visid_incap_", "nlbi_"],
    htmlMarkers: [],
  },
  {
    name: "Akamai",
    vendor: "Akamai Technologies",
    headers: {
      "x-akamai-transformed": "",
      "x-akamai-request-id": "",
      "akamai-origin-hop": "",
    },
    codes: [403],
    bodyPatterns: [
      "Reference #",
      "Access Denied",
      "You don't have permission to access",
      "AkamaiGHost",
    ],
    cookies: [],
    htmlMarkers: [],
  },
  {
    name: "F5 BIG-IP ASM",
    vendor: "F5 Networks",
    headers: {
      "x-waf-status": "",
      "x-cnection": "",
    },
    codes: [200, 403],
    bodyPatterns: [
      "The requested URL was rejected",
      "Please consult with your administrator",
      "Your support ID is:",
      "Attack Signature Detected",
    ],
    cookies: ["TS[0-9a-f]+", "F5_ST", "BIGipServer"],
    htmlMarkers: [],
  },
  {
    name: "Sucuri",
    vendor: "Sucuri / GoDaddy",
    headers: {
      "x-sucuri-id": "",
      "x-sucuri-cache": "",
      "server": "Sucuri/Cloudproxy",
    },
    codes: [403],
    bodyPatterns: [
      "Sucuri WebSite Firewall",
      "Access Denied - Sucuri Website Firewall",
      "CloudProxy - Sucuri",
      "Block reason:",
      "sucuri_cloudproxy_",
    ],
    cookies: ["sucuri_cloudproxy_"],
    htmlMarkers: [".sucuriscan"],
  },
  {
    name: "Barracuda",
    vendor: "Barracuda Networks",
    headers: {},
    codes: [403],
    bodyPatterns: [
      "Barracuda Web Application Firewall",
      "The requested URL is not allowed",
      "Barracuda Networks",
    ],
    cookies: [],
    htmlMarkers: [],
  },
  {
    name: "FortiWeb",
    vendor: "Fortinet",
    headers: {},
    codes: [403],
    bodyPatterns: [
      "FortiWeb Application Firewall",
      "The server is temporarily unable to service your request",
      "FortiWeb - Web Server Protected",
    ],
    cookies: [],
    htmlMarkers: [],
  },
  {
    name: "Wordfence",
    vendor: "Defiant, Inc.",
    headers: {},
    codes: [403, 503],
    bodyPatterns: [
      "Generated by Wordfence",
      "Your access to this site has been limited",
      "Block Technical Data",
    ],
    cookies: ["wfvt_"],
    htmlMarkers: [],
  },
  {
    name: "Wallarm",
    vendor: "Wallarm, Inc.",
    headers: {},
    codes: [403],
    bodyPatterns: [
      "Wallarm WAF",
      "Request blocked by Wallarm",
    ],
    cookies: [],
    htmlMarkers: [],
  },
  {
    name: "Radware",
    vendor: "Radware, Ltd.",
    headers: {
      "x-sl-compstate": "",
    },
    codes: [403],
    bodyPatterns: [
      "Unauthorized Activity Has Been Detected",
      "Unsuccessful due to suspicious activity",
    ],
    cookies: [],
    htmlMarkers: [],
  },
  {
    name: "Edgecast / Verizon",
    vendor: "Verizon Digital Media",
    headers: {
      "server": "ECD",
    },
    codes: [403],
    bodyPatterns: [
      "Please contact the site administrator",
      "Access Denied.",
    ],
    cookies: [],
    htmlMarkers: [],
  },
];

/**
 * Analyze an HTTP response for WAF signatures.
 * Accepts a simplified response shape so it works with both
 * raw HTTP and sqlmap's output.
 */
export function detectWaf(response: {
  status: number;
  headers: Record<string, string>;
  body: string;
  setCookie?: string[];
}): WafDetectionResult {
  const matches: Array<{ name: string; confidence: number }> = [];
  const evidence: string[] = [];

  const headerKeys = Object.keys(response.headers).map((k) => k.toLowerCase());
  const bodyLower = response.body.toLowerCase();

  for (const sig of WAF_SIGNATURES) {
    let score = 0;
    let maxScore = 0;
    const localEvidence: string[] = [];

    // Check status codes
    maxScore += 15;
    if (sig.codes.includes(response.status)) {
      score += 15;
      localEvidence.push(`HTTP ${response.status} matches known block code`);
    }

    // Check headers
    for (const [hName, hValue] of Object.entries(sig.headers)) {
      maxScore += 10;
      const key = hName.toLowerCase();
      if (headerKeys.includes(key)) {
        const actualValue = response.headers[key] ?? response.headers[hName] ?? "";
        if (hValue === "" || actualValue.toLowerCase().includes(hValue.toLowerCase())) {
          score += 10;
          localEvidence.push(`Header ${hName}: ${actualValue}`);
        }
      }
    }

    // Check body patterns
    for (const pattern of sig.bodyPatterns) {
      maxScore += 12;
      try {
        if (new RegExp(pattern, "i").test(bodyLower)) {
          score += 12;
          localEvidence.push(`Body matches: ${pattern.slice(0, 50)}`);
          break; // One body match is enough for scoring
        }
      } catch {
        // Invalid regex — skip
      }
    }

    // Check cookies
    for (const cookie of sig.cookies) {
      maxScore += 8;
      const cookieLower = cookie.toLowerCase();
      const allCookies = response.setCookie ?? [];
      const cookieHeader = response.headers["set-cookie"] ?? "";
      const allCookieText = [...allCookies, cookieHeader].join(";").toLowerCase();
      if (new RegExp(cookieLower, "i").test(allCookieText)) {
        score += 8;
        localEvidence.push(`Cookie matches: ${cookie}`);
      }
    }

    // Check HTML markers
    for (const marker of sig.htmlMarkers) {
      maxScore += 5;
      if (bodyLower.includes(marker.toLowerCase())) {
        score += 5;
        localEvidence.push(`HTML marker: ${marker}`);
      }
    }

    if (score > 0) {
      const confidence = Math.min(100, Math.round((score / Math.max(1, maxScore)) * 100));
      matches.push({ name: sig.name, confidence });
      if (confidence >= 30) {
        evidence.push(...localEvidence);
      }
    }
  }

  matches.sort((a, b) => b.confidence - a.confidence);

  const top = matches[0];
  if (top && top.confidence >= 30) {
    const sig = WAF_SIGNATURES.find((s) => s.name === top.name);
    return {
      detected: true,
      name: top.name,
      vendor: sig?.vendor ?? null,
      confidence: top.confidence,
      evidence: [...new Set(evidence)],
      allMatches: matches.filter((m) => m.confidence >= 10),
    };
  }

  return {
    detected: false,
    name: null,
    vendor: null,
    confidence: 0,
    evidence: [],
    allMatches: matches.filter((m) => m.confidence >= 10),
  };
}
